services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/application_default_credentials.json
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - K_SERVICE=${K_SERVICE}
      - JWT_ISS=${JWT_ISS}
      - JWT_KEY=${JWT_KEY}
      - JWT_VALID_FOR_SECONDS=${JWT_VALID_FOR_SECONDS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - PORT=${PORT}
    volumes:
      # See https://cloud.google.com/docs/authentication/application-default-credentials#personal
      - ~/.config/gcloud/application_default_credentials.json:/tmp/application_default_credentials.json
    depends_on:
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - PORT=${PORT}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:15"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
