//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ArticleComment = newArticleCommentTable("public", "article_comment", "")

type articleCommentTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	AuthorID  postgres.ColumnString
	ArticleID postgres.ColumnString
	Body      postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ArticleCommentTable struct {
	articleCommentTable

	EXCLUDED articleCommentTable
}

// AS creates new ArticleCommentTable with assigned alias
func (a ArticleCommentTable) AS(alias string) *ArticleCommentTable {
	return newArticleCommentTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ArticleCommentTable with assigned schema name
func (a ArticleCommentTable) FromSchema(schemaName string) *ArticleCommentTable {
	return newArticleCommentTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ArticleCommentTable with assigned table prefix
func (a ArticleCommentTable) WithPrefix(prefix string) *ArticleCommentTable {
	return newArticleCommentTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ArticleCommentTable with assigned table suffix
func (a ArticleCommentTable) WithSuffix(suffix string) *ArticleCommentTable {
	return newArticleCommentTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newArticleCommentTable(schemaName, tableName, alias string) *ArticleCommentTable {
	return &ArticleCommentTable{
		articleCommentTable: newArticleCommentTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newArticleCommentTableImpl("", "excluded", ""),
	}
}

func newArticleCommentTableImpl(schemaName, tableName, alias string) articleCommentTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		AuthorIDColumn  = postgres.StringColumn("author_id")
		ArticleIDColumn = postgres.StringColumn("article_id")
		BodyColumn      = postgres.StringColumn("body")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, AuthorIDColumn, ArticleIDColumn, BodyColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{AuthorIDColumn, ArticleIDColumn, BodyColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return articleCommentTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		AuthorID:  AuthorIDColumn,
		ArticleID: ArticleIDColumn,
		Body:      BodyColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
