//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ArticleTag = newArticleTagTable("public", "article_tag", "")

type articleTagTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Name      postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ArticleTagTable struct {
	articleTagTable

	EXCLUDED articleTagTable
}

// AS creates new ArticleTagTable with assigned alias
func (a ArticleTagTable) AS(alias string) *ArticleTagTable {
	return newArticleTagTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ArticleTagTable with assigned schema name
func (a ArticleTagTable) FromSchema(schemaName string) *ArticleTagTable {
	return newArticleTagTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ArticleTagTable with assigned table prefix
func (a ArticleTagTable) WithPrefix(prefix string) *ArticleTagTable {
	return newArticleTagTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ArticleTagTable with assigned table suffix
func (a ArticleTagTable) WithSuffix(suffix string) *ArticleTagTable {
	return newArticleTagTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newArticleTagTable(schemaName, tableName, alias string) *ArticleTagTable {
	return &ArticleTagTable{
		articleTagTable: newArticleTagTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newArticleTagTableImpl("", "excluded", ""),
	}
}

func newArticleTagTableImpl(schemaName, tableName, alias string) articleTagTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		NameColumn      = postgres.StringColumn("name")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, NameColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, CreatedAtColumn}
	)

	return articleTagTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
