//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ArticleFavorite = newArticleFavoriteTable("public", "article_favorite", "")

type articleFavoriteTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	UserID    postgres.ColumnString
	ArticleID postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ArticleFavoriteTable struct {
	articleFavoriteTable

	EXCLUDED articleFavoriteTable
}

// AS creates new ArticleFavoriteTable with assigned alias
func (a ArticleFavoriteTable) AS(alias string) *ArticleFavoriteTable {
	return newArticleFavoriteTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ArticleFavoriteTable with assigned schema name
func (a ArticleFavoriteTable) FromSchema(schemaName string) *ArticleFavoriteTable {
	return newArticleFavoriteTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ArticleFavoriteTable with assigned table prefix
func (a ArticleFavoriteTable) WithPrefix(prefix string) *ArticleFavoriteTable {
	return newArticleFavoriteTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ArticleFavoriteTable with assigned table suffix
func (a ArticleFavoriteTable) WithSuffix(suffix string) *ArticleFavoriteTable {
	return newArticleFavoriteTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newArticleFavoriteTable(schemaName, tableName, alias string) *ArticleFavoriteTable {
	return &ArticleFavoriteTable{
		articleFavoriteTable: newArticleFavoriteTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newArticleFavoriteTableImpl("", "excluded", ""),
	}
}

func newArticleFavoriteTableImpl(schemaName, tableName, alias string) articleFavoriteTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		UserIDColumn    = postgres.StringColumn("user_id")
		ArticleIDColumn = postgres.StringColumn("article_id")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, ArticleIDColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, ArticleIDColumn, CreatedAtColumn}
	)

	return articleFavoriteTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		ArticleID: ArticleIDColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
